sudo: required
services:
  - docker
before_install:
  - docker build -t martinshell/docker-react -f Dockerfile.dev .
script:
    - script:
        - docker run martinshell/docker-react npm run test -- --coverage