sudo: required
services:
  - docker
before_install:
  - docker build -t martinshell/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true martinshell/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-779755479568"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
